server:
  servlet:
    context-path: /api
  port: '8081'
  
spring:
  datasource:
    password: q1w2e3r4
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: dbuser
    url: jdbc:mysql://localhost:3306/project?serverTimezone=UTC
  jpa:
    properties:
      hibernate:
        "[format_sql]": 'true'
        "[show_sql]": 'true'
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: false

hibernate:
  use-new-id-generator-mappings:false

mybatis:
  type-aliases-package: com.example.mappertut.model
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: 'true'
    
logging:
  level:
    jdbc:
      audit: 'off'
      connection: 'off'
      sqlonly: info
      resultset: 'off'
      resultsettable: info
      sqltiming: 'off'
