server:
  servlet:
    context-path: /api
  port: '8081'
  
spring:
  datasource:
    password: q1w2e3r4
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: dbuser
    url: jdbc:mysql://localhost:3306/project?serverTimezone=UTC
  jpa:
    properties:
      hibernate:
        "[format_sql]": true
        "[show_sql]": true
        "[use_sql_comments]": true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: false

hibernate:
  use-new-id-generator-mappings:false
  
file:
  uploadPath: C:/dev/upload

logging:
  level:
    "[org.hibernate.orm.jdbc.bind]": trace
